apiVersion: v1
kind: Service
metadata:
  labels:
    {{ .Values.productShortName }}.service: elasticsearch
  name: elasticsearch
spec:
  ports:
  - port: 9200
  selector:
    {{ .Values.productShortName }}.service: elasticsearch
