apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    {{ .Values.productShortName }}.service: influxdb
spec:
  ports:
    - port: 8086
  selector:
    {{ .Values.productShortName }}.service: influxdb
