apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
{{- if .Values.http.tlsSecret }}
  tls:
    - secretName: {{ .Values.http.tlsSecret }}
      hosts:
        - {{ .Values.http.host }}
{{- end }}
  rules:
  - host: {{ .Values.http.host }}
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
