apiVersion: v1
kind: Service
metadata:
  labels:
    {{ .Values.productShortName }}.service: landing
  name: landing
spec:
  ports:
  - port: 80
  selector:
    {{ .Values.productShortName }}.service: landing
