{{ if eq .Values.smtp.host "mailmock" -}}
kind: Service
apiVersion: v1
metadata:
  labels:
    {{ .Values.productShortName }}.service: mailmock
  name: mailmock
spec:
  ports:
    - port: 8143
      targetPort: 8143
      name: imap
    - port: 8025
      targetPort: 8025
      name: smtp
  selector:
    {{ .Values.productShortName }}.service: mailmock
{{- end }}
