apiVersion: v1
kind: Service
metadata:
  labels:
    {{ .Values.productShortName }}.service: memcached
  name: memcached
spec:
  ports:
  - port: 11211
  selector:
    {{ .Values.productShortName }}.service: memcached
