apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  labels:
    {{ .Values.productShortName }}.service: mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
