apiVersion: v1
kind: Service
metadata:
  labels:
    {{ .Values.productShortName }}.service: mongodb
  name: mongodb
spec:
  ports:
  - port: 27017
  selector:
    {{ .Values.productShortName }}.service: mongodb
