apiVersion: v1
kind: Service
metadata:
  name: swagger
  labels:
    {{ .Values.productShortName }}.service: swagger
spec:
  ports:
    - port: 8080
  selector:
    {{ .Values.productShortName }}.service: swagger
