apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-api
  labels:
    app: api
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 80
  selector:
    app: api
    release: {{ .Release.Name }}
