{{ range $name, $settings := $.Values.deployment.celery -}}
{{ if $settings.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" $ }}-celery-{{ $name }}
  labels:
    app: celery-{{ $name }}
    chart: {{ include "chart.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  replicas: {{ $settings.replicas | default "1" }}
  template:
    metadata:
      labels:
        app: celery-{{ $name }}
        release: {{ $.Release.Name }}
      annotations:
        # Trigger modification of deployment & restart of pods if config changes.
        checksum/config: {{ include (print $.Template.BasePath "/main-configmap.yaml") $ | sha256sum }}
    spec:
      imagePullSecrets:
{{ toYaml $.Values.image.secrets | indent 8 }}
      containers:
      - name: celery-{{ $name }}
        args:
        - bin/celery-{{ $settings.pool | default "prefork" }}
        image: {{ $.Values.image.registry }}/api:{{ $.Values.image.tag }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        env:
        - name: QUEUES
          value: "{{ range $i, $q := $settings.queues }}{{ if gt $i 0 }},{{ end }}{{ $q }}{{ end }}"
        resources:
          requests:
            memory: {{ $settings.resources.requests.memory | default "1000Mi" }}
            cpu: {{ $settings.resources.requests.cpu | default "400m" }}
          limits:
            memory: {{ $settings.resources.limits.memory | default "1000Mi" }}
            cpu: {{ $settings.resources.limits.cpu | default "1000m" }}
        volumeMounts:
        - name: {{ $.Values.productShortName }}-config
          mountPath: /etc/{{ $.Values.productShortName }}/settings/settings.py
          subPath: settings.py
{{- if $settings.preemptible }}
{{- if $.Values.preemptible.tolerations }}
      tolerations:
{{ toYaml $.Values.preemptible.tolerations | indent 8 }}
{{- end }}
{{- if $.Values.preemptible.nodeAffinity }}
      affinity:
        nodeAffinity:
{{ toYaml $.Values.preemptible.nodeAffinity | indent 10 }}
{{- end }}
{{- end }}
      terminationGracePeriodSeconds: {{ $settings.gracePeriod | default 300 }}
      volumes:
      - name: {{ $.Values.productShortName }}-config
        configMap:
          name: {{ include "chart.fullname" $ }}-{{ $.Values.productShortName }}
{{- if $.Values.nodeSelector }}
      nodeSelector:
{{ toYaml $.Values.nodeSelector | indent 8 }}
{{- end }}
---
{{ end }}
{{- end }}
