{{ if and .Values.prometheus.enabled .Values.prometheus.operator.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "chart.fullname" . }}-celery
  namespace: {{ .Values.prometheus.operator.serviceMonitor.namespace }}
  labels:
    app: celery-exporter
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.prometheus.operator.serviceMonitor.selector }}
{{ toYaml .Values.prometheus.operator.serviceMonitor.selector | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: celery-exporter
      release: {{ .Release.Name }}
  endpoints:
  - port: exporter
    interval: {{ .Values.prometheus.operator.serviceMonitor.interval }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{ end }}
