{{ if .Values.prometheus.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{ .Values.productShortName }}.service: celery-exporter
  annotations:
    prometheus.io/path: /
    prometheus.io/port: "8888"
    prometheus.io/scrape: "true"
  name: celery-exporter
spec:
  ports:
  - name: exporter
    port: 8888
  selector:
    {{ .Values.productShortName }}.service: celery-exporter
{{- end }}
