{{ $values := .Values -}}
{{ range $name, $settings := $values.deployment.celery -}}
{{ if and $settings.enabled $settings.autoscaling.enabled -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "chart.fullname" $ }}-celery-{{ $name }}
  labels:
    app: celery-{{ $name }}
    chart: {{ include "chart.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ include "chart.fullname" $ }}-celery-{{ $name }}
  minReplicas: {{ $settings.autoscaling.minReplicas }}
  maxReplicas: {{ $settings.autoscaling.maxReplicas }}
  metrics:
{{- if $settings.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ $settings.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- if $settings.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ $settings.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
{{- if and $.Values.prometheus.enabled $.Values.prometheus.operator.enabled }}
    - type: Object
      object:
        target:
          apiVersion: extensions/v1beta1
          kind: Deployment
          name: {{ include "chart.fullname" $ }}-celery-{{ $name }}
        metricName: hpa_custom_metrics_deployment_queues_length
        targetValue: 10
{{- end }}
---
{{ end }}
{{- end }}
