apiVersion: v1
kind: Service
metadata:
  name: gocky
  labels:
    {{ .Values.productShortName }}.service: gocky
spec:
  ports:
    - name: gocky-relay
      port: 9097
    - name: influxdb-relay
      port: 9096
  selector:
    {{ .Values.productShortName }}.service: gocky
