{{ if and (eq .Values.influxdb.host "influxdb") (eq (toString .Values.influxdb.port) "8086") -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb
  labels:
    {{ .Values.productShortName }}.service: influxdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
{{- end }}
