apiVersion: v1
kind: Service
metadata:
  labels:
    {{ .Values.productShortName }}.service: kibana
  name: kibana
spec:
  ports:
  - port: 5601
  selector:
    {{ .Values.productShortName }}.service: kibana
