apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-kibana
  labels:
    app: kibana
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: kibana
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        image: kibana:5.6.10
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 150Mi
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
