apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-kibana
  labels:
    app: kibana
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 5601
  selector:
    app: kibana
    release: {{ .Release.Name }}
