{{ if eq .Values.smtp.host "" -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "chart.fullname" . }}-mailmock
  labels:
    app: mailmock
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 8143
      targetPort: 8143
      name: imap
    - port: 8025
      targetPort: 8025
      name: smtp
  selector:
    app: mailmock
    release: {{ .Release.Name }}
{{- end }}
