{{ if and (eq .Values.mongodb.host "mongodb") (eq (toString .Values.mongodb.port) "27017") -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  labels:
    {{ .Values.productShortName }}.service: mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
{{- end }}
