{{ if and .Values.prometheus.enabled .Values.prometheus.operator.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-hpa-custom-metrics-celery
  namespace: {{ .Values.prometheus.operator.rules.namespace }}
  labels:
{{- if .Values.prometheus.operator.rules.selector }}
{{ toYaml .Values.prometheus.operator.rules.selector | indent 4 }}
{{- end }}
spec:
  groups:
  - name: hpa
    interval: {{ .Values.prometheus.operator.rules.interval }}
    rules:
  {{- range $name, $settings := .Values.deployment.celery }}
  {{- if and $settings.enabled $settings.autoscaling.enabled }}
    - expr: 'label_replace(sum(max(rabbitmq_queue_messages{namespace="{{ $.Release.Namespace }}", queue=~"{{ range $i, $q := $settings.queues }}{{ if gt $i 0 }}|{{ end }}{{ $q }}{{ end }}"}) by (namespace, queue)) by (namespace), "deployment", "celery-{{ $name }}", "", "")'
      record: hpa_custom_metrics_deployment_queues_length
  {{- end }}
  {{- end }}
{{- end }}
