apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    {{ .Values.productShortName }}.service: swagger
  name: swagger
spec:
  replicas: 1
  template:
    metadata:
      labels:
        {{ .Values.productShortName }}.service: swagger
    spec:
      containers:
      - name: swagger
        env:
        - name: API_URL
          value: /api/v1/spec
        image: mist/swagger-ui
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            memory: 50Mi
            cpu: 200m
          requests:
            memory: 20Mi
            cpu: 10m
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
