apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-swagger
  labels:
    app: swagger
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: swagger
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: swagger
        env:
        - name: API_URL
          value: /api/v1/spec
        image: mist/swagger-ui
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            memory: 50Mi
            cpu: 200m
          requests:
            memory: 20Mi
            cpu: 10m
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
