apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-swagger
  labels:
    app: swagger
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 8080
  selector:
    app: swagger
    release: {{ .Release.Name }}
