apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-traefik
  labels:
    app: traefik
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: traefik
      port: 80
    - name: traefik-admin
      port: 8080
  selector:
    app: traefik
    release: {{ .Release.Name }}
