apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-ui
  labels:
    app: ui
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 80
  selector:
    app: ui
    release: {{ .Release.Name }}
