ARG SRC_IMG
FROM $SRC_IMG
COPY  \
    ./api/v2/mist_api_v2/test/test_auth_controller.py \
    ./api/v2/mist_api_v2/test/test_clouds_controller.py \
    ./api/v2/mist_api_v2/test/test_clusters_controller.py \
    ./api/v2/mist_api_v2/test/test_datapoints_controller.py \
    ./api/v2/mist_api_v2/test/test_images_controller.py \
    ./api/v2/mist_api_v2/test/test_jobs_controller.py \
    ./api/v2/mist_api_v2/test/test_keys_controller.py \
    ./api/v2/mist_api_v2/test/test_locations_controller.py \
    ./api/v2/mist_api_v2/test/test_machines_controller.py \
    ./api/v2/mist_api_v2/test/test_networks_controller.py \
    # ./api/v2/mist_api_v2/test/test_orgs_controller.py \
     ./api/v2/mist_api_v2/test/test_rules_controller.py \
     ./api/v2/mist_api_v2/test/test_schedules_controller.py \
    ./api/v2/mist_api_v2/test/test_scripts_controller.py \
    ./api/v2/mist_api_v2/test/test_secrets_controller.py \
    ./api/v2/mist_api_v2/test/test_sizes_controller.py \
    ./api/v2/mist_api_v2/test/test_snapshots_controller.py \
    ./api/v2/mist_api_v2/test/test_tags_controller.py \
    ./api/v2/mist_api_v2/test/test_users_controller.py \
    ./api/v2/mist_api_v2/test/test_volumes_controller.py \
    ./api/v2/mist_api_v2/test/test_zones_controller.py \
    misttests/integration/api/main/v2/
