ARG SRC_IMG
FROM $SRC_IMG
COPY ./api/v2/mist_api_v2/test/setup misttests/integration/api/v2/
COPY ./api/v2/mist_api_v2/test/test_clouds_controller.py misttests/integration/api/v2/
COPY ./api/v2/mist_api_v2/test/test_clusters_controller.py misttests/integration/api/v2/