#!/bin/bash

init_vars() {
BASE_DIR=`pwd`
BUILD_DIR=${BASE_DIR}/var/tmp/build
RJS_EXEC=${BUILD_DIR}/r.js/r.js
CURRENT_BRANCH=$(git branch | awk '/\*/ { print $2; }')
time_now=`date +"%s"`

}

install_rjs() {

mkdir -p var/tmp/build
cd ${BUILD_DIR}

if [ -d r.js ]; then
    echo "R.js already cloned"
else
    git clone https://github.com/jrburke/r.js
fi
cd r.js
node dist.js
cd ${BASE_DIR}
}

build_templates() {
cd ${BASE_DIR}
./scripts/hcomp.sh $(pwd)
cd ${BASE_DIR}
}

build_app(){
cd ${BASE_DIR}
files=`ls -1tr src/mist/io/static/build/mist-*`
node ${RJS_EXEC} -o src/mist/io/static/app.build.js out=src/mist/io/static/build/mist-${time_now}.js
APP_CHANGED=`diff src/mist/io/static/build/mist-${time_now}.js src/mist/io/static/build/mist.js`

if [ "$APP_CHANGED" ]; then
    CHANGED="True"
    for x in $files
    do
        git rm -f $x
    done
    ln -sf src/mist/io/static/build/mist.js src/mist/io/static/build/mist-${time_now}.js
else
    rm src/mist/io/static/build/mist-${time_now}.js
fi

cd ${BASE_DIR}
}

init_vars

install_rjs

build_templates

build_app